[versions]
androidBuildTools = "7.3.1"
detekt = "1.22.0"
jetbrainsCompose = "1.3.0-rc01"
kotlin = "1.7.20"
decompose = "1.0.0-beta-01"
coroutines = "1.6.4"
jetbrainsKotlinxSerialization = "1.4.1"
androidxCore = "1.3.2"
androidxComposeActivity = "1.6.1"
androidxTestCore = "1.4.0"
koin = "3.2.2"
okio = "3.2.0"
kodein = "7.16.0"
kermit = "1.2.2"
sqlDelight = "1.5.4"
loadTheImage = "1.0.5"
coilCompose = "2.2.2"
accompanist = "0.28.0"

[libraries]

#Gradle Plugins
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-compose = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "jetbrainsCompose" }

#KotlinX
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrainsKotlinxSerialization" }
jetbrains-kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "jetbrainsKotlinxSerialization" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }


#AndroidX
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxComposeActivity" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }

#Accompanist
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

#ImageLoading
load-the-image = { module = "com.github.ltttttttttttt:load-the-image", version.ref = "loadTheImage" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

#Kodein
kodein-di = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-di-framework-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
kodein-di-framework-android-x = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }

#Kermit - logger
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

#SQLDelight
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
squareup-sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
squareup-sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
squareup-sqldelight-extension-coroutines = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

#Decompose
arkivanov-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
arkivanov-decompose-extensions-compose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
arkivanov-essenty-parcelable = { module = "com.arkivanov.essenty:parcelable", version = "0.7.0" }

[plugins]
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
squareup-sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
